package com.emc.qe.cira.ui.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.ProgressBar;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class InstallSEDesign extends VerticalLayout {
	protected FormLayout formLayout;
	protected ComboBox osComboBox;
	protected ListSelect hostList;
	protected TextField hostInput;
	protected HorizontalLayout checkBoxLayout;
	protected CheckBox hostDetail;
	protected CheckBox installSE;
	protected ListSelect versionList;
	protected Button submit;
	protected HorizontalLayout dataLayout;
	protected Grid hostGrid;
	protected ProgressBar installProgress;

	public InstallSEDesign() {
		Design.read(this);
	}
}
