package com.emc.qe.cira.ui.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class InstallSEDesign extends VerticalLayout {
	protected FormLayout installSE_form;
	protected ComboBox os_combobox;
	protected ListSelect host_list;
	protected TextField host_input;
	protected HorizontalLayout h_checkbox_layout;
	protected CheckBox host_details_cb;
	protected CheckBox install_se_cb;
	protected ListSelect seVersion_list;
	protected Button submit;
	protected Panel panel;
	protected Grid data_grid;

	public InstallSEDesign() {
		Design.read(this);
	}
}
