package com.emc.qe.cira.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Host generated by hbm2java
 */
@Entity
@Table(name = "host_detail", schema = "public")
public class Host implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private long id;
	private String hostName;
	private String seVersion;
	private String hostOs;
	private String hostOsVersion;
	private String hostIpAddress;

	public Host() {
	}

	@Column(name = "host_name", nullable = false, length = 30)
	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	@Column(name = "se_version", length = 30)
	public String getSeVersion() {
		return this.seVersion;
	}

	public void setSeVersion(String seVersion) {
		this.seVersion = seVersion;
	}

	@Column(name = "host_os", length = 30)
	public String getHostOs() {
		return this.hostOs;
	}

	public void setHostOs(String hostOs) {
		this.hostOs = hostOs;
	}

	@Column(name = "host_os_version")
	public String getHostOsVersion() {
		return this.hostOsVersion;
	}

	public void setHostOsVersion(String hostOsVersion) {
		this.hostOsVersion = hostOsVersion;
	}

	@Column(name = "host_ip_address", length = 30)
	public String getHostIpAddress() {
		return this.hostIpAddress;
	}

	public void setHostIpAddress(String hostIpAddress) {
		this.hostIpAddress = hostIpAddress;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((hostName == null) ? 0 : hostName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Host other = (Host) obj;
		if (hostName == null) {
			if (other.hostName != null)
				return false;
		} else if (!hostName.equals(other.hostName))
			return false;
		return true;
	}

	@Id
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

}
