package com.emc.qe.cira.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import javax.persistence.Table;

/**
 * Host generated by hbm2java
 */
@Entity
@Table(name = "host_type", schema = "public")

public class HostType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private long id;
	private String hostName;
	private String hostOs;
	
	public HostType() {
	}

	@Column(name = "host_name", nullable = false, length = 30)
	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	
	@Column(name = "host_os", length = 30)
	public String getHostOs() {
		return this.hostOs;
	}

	public void setHostOs(String hostOs) {
		this.hostOs = hostOs;
	}


	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((hostName == null) ? 0 : hostName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		HostType other = (HostType) obj;
		if (hostName == null) {
			if (other.hostName != null)
				return false;
		} else if (!hostName.equals(other.hostName))
			return false;
		return true;
	}

	@Id
	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

}
