package com.emc.qe.cira.model;
// Generated Dec 11, 2016 10:06:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SeInstallStatus generated by hbm2java
 */
@Entity
@Table(name = "se_install_status", schema = "public")
public class SeInstallStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String hostName;
	private Boolean updateProgress;

	public SeInstallStatus() {
	}

	public SeInstallStatus(String hostName) {
		this.hostName = hostName;
	}

	public SeInstallStatus(String hostName, Boolean updateProgress) {
		this.hostName = hostName;
		this.updateProgress = updateProgress;
	}

	@Column(name = "host_name", unique = true, nullable = false, length = 30)
	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	@Column(name = "update_progress")
	public Boolean getUpdateProgress() {
		return this.updateProgress;
	}

	public void setUpdateProgress(Boolean updateProgress) {
		this.updateProgress = updateProgress;
	}
	
	@Id
	public long getId() {
		return id;
	}


	public void setId(long id) {
		this.id = id;
	}

}
